### ISSUE TITLE
Layout for Bone

### ISSUE THREAD

**Issue by BrainStone** [TestudoAquatilis/wasd-neo-keyboard#1]
Hi! Thank you very much for this amazing template for the Neo2 layout.

I was looking into getting a custom keyboard from WASD Keyboards and noticed the newer [Bone](https://www.neo-layout.org/Layouts/bone/) layout on the Neo homepage.  
Frankly speaking I am not at all familiar with working with SVGs, nor keyboard layouts and was wondering if you were willing to adjust this great layout template to the Bone layout as well.

**Comment by TestudoAquatilis** [comment]
Hello, although I understand the problem, it is unlikely that I will fix that at all: I'm very used to neo2 now and it took some time to arrange this layout and bone2 seems to have at least 3 layers rearranged (I am also not so efficient in designing). In case you are motivated at some point in time, I can only recommend using Inkskape (that is what WASD recommended and worked quite well for me).

**Comment by BrainStone** [comment]
Awww. Very disapointing, but I do understand!
